[package]
name = "jake_crates_io_test"
version = "0.1.0"
edition = "2021"
description = "Junk crate. Just testing crates.io upload."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
